version: '2'
services:
  www_1:
    container_name: www_1
    image: luxsource/nginx-php
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./www/1:/www
    restart: always
  www_2:
    container_name: www_2
    image: luxsource/nginx-php
    build: .
    ports:
      - "8082:80"
    volumes:
      - ./www/2:/www
      - ./www/custom.nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - "NOTCLEARENV=1"
    restart: always
